# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: external.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "external.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x65xternal.proto\x12\x08\x65xternal"?\n\x12SignalBatchRequest\x12)\n\x08requests\x18\x01 \x03(\x0b\x32\x17.external.SignalRequest"a\n\rSignalRequest\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x1a\n\x12normalized_outcome\x18\x02 \x01(\t\x12\x12\n\nas_of_time\x18\x03 \x01(\t\x12\r\n\x05query\x18\x04 \x01(\t",\n\x13SignalBatchResponse\x12\x15\n\rprobabilities\x18\x01 \x03(\x01\x32`\n\rSignalService\x12O\n\x10GetProbabilities\x12\x1c.external.SignalBatchRequest\x1a\x1d.external.SignalBatchResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "external_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SIGNALBATCHREQUEST"]._serialized_start = 28
    _globals["_SIGNALBATCHREQUEST"]._serialized_end = 91
    _globals["_SIGNALREQUEST"]._serialized_start = 93
    _globals["_SIGNALREQUEST"]._serialized_end = 190
    _globals["_SIGNALBATCHRESPONSE"]._serialized_start = 192
    _globals["_SIGNALBATCHRESPONSE"]._serialized_end = 236
    _globals["_SIGNALSERVICE"]._serialized_start = 238
    _globals["_SIGNALSERVICE"]._serialized_end = 334
# @@protoc_insertion_point(module_scope)
