# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import external_pb2 as external__pb2

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in external_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SignalServiceStub(object):
    """The service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProbabilities = channel.unary_unary(
            "/external.SignalService/GetProbabilities",
            request_serializer=external__pb2.SignalBatchRequest.SerializeToString,
            response_deserializer=external__pb2.SignalBatchResponse.FromString,
            _registered_method=True,
        )


class SignalServiceServicer(object):
    """The service definition"""

    def GetProbabilities(self, request, context):
        """Batch RPC: you send N rows, get N probabilities back in order"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SignalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetProbabilities": grpc.unary_unary_rpc_method_handler(
            servicer.GetProbabilities,
            request_deserializer=external__pb2.SignalBatchRequest.FromString,
            response_serializer=external__pb2.SignalBatchResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "external.SignalService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("external.SignalService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SignalService(object):
    """The service definition"""

    @staticmethod
    def GetProbabilities(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/external.SignalService/GetProbabilities",
            external__pb2.SignalBatchRequest.SerializeToString,
            external__pb2.SignalBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
