[feeds]
rss = [
	"https://feeds.megaphone.fm/ESP9520742908",
	"https://www.theguardian.com/football/series/footballweekly/podcast.xml",
	"https://feeds.acast.com/public/shows/681ccd8a24b1daf01a7207ba",
	"https://feeds.simplecast.com/KV1aCFKS",
	"https://feeds.acast.com/public/shows/6818be7d1d28d62313ac8ef3",
	"https://podcast.global.com/show/3382902/episodes/feed",
	"https://feeds.acast.com/public/shows/6818cfc81d28d62313b34379",
	"https://podcasts.files.bbci.co.uk/p02nrsln.rss",
	"https://www.theguardian.com/football/series/footballweekly/podcast.xml",
	"https://feeds.acast.com/public/shows/681887451d28d623139a0fc9",
	"https://feeds.acast.com/public/shows/681cc9bc5acb8b715f1eb2f6",
	"https://feeds.acast.com/public/shows/681ccb505acb8b715f1f1330",
	"https://feeds.acast.com/public/shows/6819aed5eb146d8e3506a450",
	"https://feeds.acast.com/public/shows/681ccc398b1f3232bc1e68ae",
	"https://feeds.acast.com/public/shows/6818cd43eb146d8e35d312c7",
	"https://feeds.acast.com/public/shows/d2a98018-244b-4999-9a83-9c2b9d43a1e3",
	"https://feeds.megaphone.fm/GLT8847082992",
	"https://feeds.acast.com/public/shows/8af0c347-5e6e-48e2-8fae-3f4e765c84ab",
	"https://feeds.acast.com/public/shows/681cccd63e6644d7a3b3065c",
	"https://feeds.acast.com/public/shows/62e90af8d40557001270a30e",
	"https://feeds.megaphone.fm/wrightys-house",
	"https://feeds.acast.com/public/shows/6242e9f71c8beb00139400a6",
	"https://feeds.acast.com/public/shows/deafe434-0a5c-4762-bc95-b11e2ce6be4e",
]
