"""Fix source_id field type and create missing tables

Revision ID: 0a9c04660fbb
Revises: fix_datetime_fields
Create Date: 2025-09-13 15:53:51.021435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0a9c04660fbb'
down_revision: Union[str, None] = 'fix_datetime_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lu_market_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ominari'
    )
    op.create_table('lu_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ominari'
    )
    op.create_table('lu_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ominari'
    )
    op.create_table('lu_sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ominari'
    )
    op.create_table('lu_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['ominari.lu_sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ominari'
    )
    op.create_table('markets_normalized',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=66), nullable=False),
    sa.Column('sport_id', sa.SmallInteger(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('market_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('winning_outcome_id', sa.SmallInteger(), nullable=True),
    sa.Column('market_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['ominari.lu_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['ominari.lu_teams.id'], ),
    sa.ForeignKeyConstraint(['market_type_id'], ['ominari.lu_market_types.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['ominari.lu_sports.id'], ),
    sa.ForeignKeyConstraint(['winning_outcome_id'], ['ominari.lu_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ominari'
    )
    with op.batch_alter_table('markets_normalized', schema='ominari') as batch_op:
        batch_op.create_index(batch_op.f('ix_ominari_markets_normalized_source_id'), ['source_id'], unique=False)

    op.create_table('odds_normalized',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('outcome_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('odds_decimal', sa.Float(), nullable=False),
    sa.Column('odds_american', sa.Integer(), nullable=True),
    sa.Column('implied_probability', sa.Float(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['ominari.markets_normalized.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['ominari.lu_outcomes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ominari.lu_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ominari'
    )
    with op.batch_alter_table('paper_trading_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pts_created_at'))
        batch_op.drop_index(batch_op.f('idx_pts_status'))

    op.drop_table('paper_trading_sessions')
    with op.batch_alter_table('odds_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_odds_archive_market'))

    op.drop_table('odds_archive')
    op.drop_table('table_metadata')
    op.drop_table('blockchain_migration')
    with op.batch_alter_table('paper_trading_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ptp_maturity'))
        batch_op.drop_index(batch_op.f('idx_ptp_session_market'))
        batch_op.drop_index(batch_op.f('idx_ptp_status_session'))

    op.drop_table('paper_trading_positions')
    op.drop_table('market_types_lookup')
    op.drop_table('lu_sources')
    op.drop_table('alpha_signals')
    op.drop_table('lu_outcomes')
    op.drop_table('stage_transitions')
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_paper_orders_timestamp'))

    op.drop_table('paper_orders')
    op.drop_table('signal_weights')
    with op.batch_alter_table('odds_recent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_odds_recent_updated'))

    op.drop_table('odds_recent')
    op.drop_table('migration_state_v2')
    op.drop_table('odds_final')
    with op.batch_alter_table('bookmakers_lookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bookmakers_name'))

    op.drop_table('bookmakers_lookup')
    with op.batch_alter_table('odds_normalized', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_odds_normalized_lookup'))
        batch_op.drop_index(batch_op.f('idx_odds_normalized_time'))

    op.drop_table('odds_normalized')
    with op.batch_alter_table('sports_lookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sports_name'))

    op.drop_table('sports_lookup')
    with op.batch_alter_table('paper_trading_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ptt_session_time'))

    op.drop_table('paper_trading_trades')
    op.drop_table('teams')
    op.drop_table('blockchain_markets')
    with op.batch_alter_table('market_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_mn_market_name'))

    op.drop_table('market_names')
    op.drop_table('lu_bookmakers')
    op.drop_table('paper_performance')
    with op.batch_alter_table('blockchain_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_blockchain_trades_market'))

    op.drop_table('blockchain_trades')
    with op.batch_alter_table('odds_normalized_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_odds_norm_v2_composite'))
        batch_op.drop_index(batch_op.f('idx_odds_norm_v2_market_time'))

    op.drop_table('odds_normalized_v2')
    op.drop_table('lu_market_types')
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_backtest_results_signal'))

    op.drop_table('backtest_results')
    op.drop_table('markets_normalized')
    with op.batch_alter_table('outcomes_lookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_outcomes_name'))

    op.drop_table('outcomes_lookup')
    op.drop_table('signal_metadata')
    op.drop_table('archive_metadata')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_quotes_source_time'))

    op.drop_table('quotes')
    op.drop_table('paper_fills')
    with op.batch_alter_table('paper_trading_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pts_session_time'))

    op.drop_table('paper_trading_snapshots')
    with op.batch_alter_table('blockchain_odds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_blockchain_odds_market'))

    op.drop_table('blockchain_odds')
    with op.batch_alter_table('signal_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_signal_performance_signal_time'))

    op.drop_table('signal_performance')
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=66),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('sport',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('league_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('market_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('home_team',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('away_team',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('position_names',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('maturity_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_market_finished'))
        batch_op.drop_index(batch_op.f('idx_market_source_sport'))

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('overtime_source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=66),
               existing_nullable=False)
        batch_op.alter_column('odds_api_source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=66),
               existing_nullable=False)
        batch_op.alter_column('confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('odd', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=66),
               existing_nullable=False)
        batch_op.alter_column('market_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('line',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('outcome',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('bookmaker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('american_odds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('decimal_odds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('normalized_implied',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_odd_position_null'))
        batch_op.drop_index(batch_op.f('idx_odd_source'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('team_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('league',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               server_default=None,
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('league',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('team_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('odd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_odd_source'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_odd_position_null'), ['position'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('normalized_implied',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('decimal_odds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('american_odds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('bookmaker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('outcome',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('line',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('market_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('source_id',
               existing_type=sa.String(length=66),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               server_default=None,
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('odds_api_source_id',
               existing_type=sa.String(length=66),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('overtime_source_id',
               existing_type=sa.String(length=66),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_market_source_sport'), ['source', 'sport'], unique=False)
        batch_op.create_index(batch_op.f('idx_market_finished'), ['is_finished', 'maturity_date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               server_default=None,
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('maturity_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('position_names',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('away_team',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('home_team',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('market_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('league_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sport',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('source_id',
               existing_type=sa.String(length=66),
               type_=sa.TEXT(),
               nullable=True)

    op.create_table('signal_performance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signal_name', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('period', sa.TEXT(), nullable=True),
    sa.Column('n_predictions', sa.INTEGER(), nullable=True),
    sa.Column('accuracy', sa.FLOAT(), nullable=True),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('information_ratio', sa.FLOAT(), nullable=True),
    sa.Column('max_drawdown', sa.FLOAT(), nullable=True),
    sa.Column('correlations', sa.TEXT(), nullable=True),
    sa.Column('regime', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['signal_name'], ['signal_metadata.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_signal_performance_signal_time'), ['signal_name', 'timestamp'], unique=False)

    op.create_table('blockchain_odds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('market_address', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('block_number', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('buy_odds', sa.FLOAT(), nullable=True),
    sa.Column('sell_odds', sa.FLOAT(), nullable=True),
    sa.Column('liquidity', sa.FLOAT(), nullable=True),
    sa.Column('network', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blockchain_odds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_blockchain_odds_market'), ['market_address', 'timestamp'], unique=False)

    op.create_table('paper_trading_snapshots',
    sa.Column('snapshot_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('snapshot_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cash_balance', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('positions_value', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('portfolio_value', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('total_pnl', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('daily_pnl', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('win_count', sa.SMALLINT(), nullable=False),
    sa.Column('loss_count', sa.SMALLINT(), nullable=False),
    sa.Column('pending_count', sa.SMALLINT(), nullable=False),
    sa.Column('max_drawdown', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_trading_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('paper_trading_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pts_session_time'), ['session_id', 'snapshot_time'], unique=False)

    op.create_table('paper_fills',
    sa.Column('fill_id', sa.TEXT(), nullable=False),
    sa.Column('order_id', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('fill_price', sa.FLOAT(), nullable=True),
    sa.Column('fill_size', sa.FLOAT(), nullable=True),
    sa.Column('slippage', sa.FLOAT(), nullable=True),
    sa.Column('commission', sa.FLOAT(), nullable=True),
    sa.Column('market_impact', sa.FLOAT(), nullable=True),
    sa.Column('pnl', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.order_id'], ),
    sa.PrimaryKeyConstraint('fill_id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('bid_price', sa.FLOAT(), nullable=True),
    sa.Column('bid_size', sa.FLOAT(), nullable=True),
    sa.Column('ask_price', sa.FLOAT(), nullable=True),
    sa.Column('ask_size', sa.FLOAT(), nullable=True),
    sa.Column('mid_price', sa.FLOAT(), nullable=True),
    sa.Column('spread', sa.FLOAT(), nullable=True),
    sa.Column('liquidity_score', sa.FLOAT(), nullable=True),
    sa.Column('raw_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_quotes_source_time'), ['source_id', 'timestamp'], unique=False)

    op.create_table('archive_metadata',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('table_name', sa.TEXT(), nullable=True),
    sa.Column('archive_date', sa.TEXT(), nullable=True),
    sa.Column('date_range_start', sa.TEXT(), nullable=True),
    sa.Column('date_range_end', sa.TEXT(), nullable=True),
    sa.Column('row_count', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_metadata',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('version', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('parameters', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('outcomes_lookup',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('outcomes_lookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_outcomes_name'), ['name'], unique=False)

    op.create_table('markets_normalized',
    sa.Column('market_id', sa.TEXT(), nullable=True),
    sa.Column('sport_id', sa.INTEGER(), nullable=True),
    sa.Column('league', sa.TEXT(), nullable=True),
    sa.Column('home_team', sa.TEXT(), nullable=True),
    sa.Column('away_team', sa.TEXT(), nullable=True),
    sa.Column('starts_at', sa.TEXT(), nullable=True),
    sa.Column('is_finished', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports_lookup.id'], ),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signal_id', sa.TEXT(), nullable=False),
    sa.Column('stage', sa.TEXT(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('n_bets', sa.INTEGER(), nullable=True),
    sa.Column('total_return', sa.FLOAT(), nullable=True),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('max_drawdown', sa.FLOAT(), nullable=True),
    sa.Column('win_rate', sa.FLOAT(), nullable=True),
    sa.Column('avg_edge', sa.FLOAT(), nullable=True),
    sa.Column('information_ratio', sa.FLOAT(), nullable=True),
    sa.Column('t_statistic', sa.FLOAT(), nullable=True),
    sa.Column('p_value', sa.FLOAT(), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['alpha_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_backtest_results_signal'), ['signal_id'], unique=False)

    op.create_table('lu_market_types',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_normalized_v2',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('market_id', sa.TEXT(), nullable=False),
    sa.Column('bookmaker_id', sa.INTEGER(), nullable=False),
    sa.Column('outcome_id', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('market_type_id', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('line_x100', sa.INTEGER(), nullable=True),
    sa.Column('decimal_odds_x1000', sa.INTEGER(), nullable=True),
    sa.Column('american_odds', sa.INTEGER(), nullable=True),
    sa.Column('implied_x10000', sa.INTEGER(), nullable=True),
    sa.Column('inserted_at', sa.INTEGER(), server_default=sa.text("(strftime('%s', 'now'))"), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers_lookup.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets_normalized.market_id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes_lookup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_normalized_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_odds_norm_v2_market_time'), ['market_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_odds_norm_v2_composite'), ['market_id', 'bookmaker_id', 'outcome_id', 'updated_at'], unique=False)

    op.create_table('blockchain_trades',
    sa.Column('tx_hash', sa.TEXT(), nullable=False),
    sa.Column('block_number', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('buyer', sa.TEXT(), nullable=True),
    sa.Column('market_address', sa.TEXT(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('susd_paid', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('gas_used', sa.INTEGER(), nullable=True),
    sa.Column('gas_price', sa.FLOAT(), nullable=True),
    sa.Column('network', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    with op.batch_alter_table('blockchain_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_blockchain_trades_market'), ['market_address'], unique=False)

    op.create_table('paper_performance',
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('capital', sa.FLOAT(), nullable=True),
    sa.Column('positions_value', sa.FLOAT(), nullable=True),
    sa.Column('total_value', sa.FLOAT(), nullable=True),
    sa.Column('daily_pnl', sa.FLOAT(), nullable=True),
    sa.Column('total_pnl', sa.FLOAT(), nullable=True),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('max_drawdown', sa.FLOAT(), nullable=True),
    sa.Column('win_rate', sa.FLOAT(), nullable=True),
    sa.Column('avg_win', sa.FLOAT(), nullable=True),
    sa.Column('avg_loss', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('lu_bookmakers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_names',
    sa.Column('market_id', sa.VARCHAR(length=68), nullable=False),
    sa.Column('market_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('home_team', sa.VARCHAR(length=100), nullable=True),
    sa.Column('away_team', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('market_id')
    )
    with op.batch_alter_table('market_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_mn_market_name'), ['market_name'], unique=False)

    op.create_table('blockchain_markets',
    sa.Column('market_address', sa.TEXT(), nullable=False),
    sa.Column('game_id', sa.TEXT(), nullable=False),
    sa.Column('game_label', sa.TEXT(), nullable=True),
    sa.Column('maturity_date', sa.INTEGER(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('normalized_odds', sa.TEXT(), nullable=True),
    sa.Column('creation_block', sa.INTEGER(), nullable=True),
    sa.Column('creation_tx', sa.TEXT(), nullable=True),
    sa.Column('network', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('market_address')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('team_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('paper_trading_trades',
    sa.Column('trade_id', sa.INTEGER(), nullable=False),
    sa.Column('position_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('trade_type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('stake_delta', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('odds', sa.NUMERIC(precision=6, scale=3), nullable=False),
    sa.Column('fee_amount', sa.NUMERIC(precision=8, scale=2), nullable=False),
    sa.Column('traded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['paper_trading_positions.position_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['paper_trading_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    with op.batch_alter_table('paper_trading_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ptt_session_time'), ['session_id', 'traded_at'], unique=False)

    op.create_table('sports_lookup',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sports_lookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sports_name'), ['name'], unique=False)

    op.create_table('odds_normalized',
    sa.Column('market_id', sa.VARCHAR(length=68), nullable=False),
    sa.Column('bookmaker_id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('market_type_id', sa.INTEGER(), nullable=False),
    sa.Column('outcome_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('line_x100', sa.SMALLINT(), nullable=True),
    sa.Column('decimal_odds_x1000', sa.SMALLINT(), nullable=False),
    sa.Column('american_odds', sa.SMALLINT(), nullable=True),
    sa.Column('implied_x10000', sa.SMALLINT(), nullable=True),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('market_id', 'bookmaker_id', 'outcome_id', 'updated_at')
    )
    with op.batch_alter_table('odds_normalized', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_odds_normalized_time'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_odds_normalized_lookup'), ['market_id', 'outcome_id', 'updated_at'], unique=False)

    op.create_table('bookmakers_lookup',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('bookmakers_lookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_bookmakers_name'), ['name'], unique=False)

    op.create_table('odds_final',
    sa.Column('market_id', sa.VARCHAR(length=68), nullable=False),
    sa.Column('outcome', sa.INTEGER(), nullable=False),
    sa.Column('final_odds_x1000', sa.INTEGER(), nullable=False),
    sa.Column('min_odds_x1000', sa.INTEGER(), nullable=False),
    sa.Column('max_odds_x1000', sa.INTEGER(), nullable=False),
    sa.Column('avg_odds_x1000', sa.INTEGER(), nullable=False),
    sa.Column('update_count', sa.INTEGER(), nullable=False),
    sa.Column('last_updated', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('market_id', 'outcome')
    )
    op.create_table('migration_state_v2',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('last_processed_rowid', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_rows', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('started_at', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_recent',
    sa.Column('market_id', sa.VARCHAR(length=68), nullable=False),
    sa.Column('outcome', sa.INTEGER(), nullable=False),
    sa.Column('odds_x1000', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('market_id', 'outcome', 'updated_at')
    )
    with op.batch_alter_table('odds_recent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_odds_recent_updated'), ['updated_at'], unique=False)

    op.create_table('signal_weights',
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('weights', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('performance_window', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('paper_orders',
    sa.Column('order_id', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('source_id', sa.TEXT(), nullable=False),
    sa.Column('market_type', sa.TEXT(), nullable=True),
    sa.Column('bet_name', sa.TEXT(), nullable=True),
    sa.Column('side', sa.TEXT(), nullable=True),
    sa.Column('size', sa.FLOAT(), nullable=True),
    sa.Column('limit_price', sa.FLOAT(), nullable=True),
    sa.Column('signal_name', sa.TEXT(), nullable=True),
    sa.Column('expected_edge', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_paper_orders_timestamp'), ['timestamp'], unique=False)

    op.create_table('stage_transitions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signal_id', sa.TEXT(), nullable=False),
    sa.Column('from_stage', sa.TEXT(), nullable=True),
    sa.Column('to_stage', sa.TEXT(), nullable=True),
    sa.Column('transition_date', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('metrics', sa.TEXT(), nullable=True),
    sa.Column('approved_by', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['alpha_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lu_outcomes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alpha_signals',
    sa.Column('signal_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('formula', sa.TEXT(), nullable=True),
    sa.Column('parameters', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('current_stage', sa.TEXT(), nullable=True),
    sa.Column('stage_history', sa.TEXT(), nullable=True),
    sa.Column('performance_metrics', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('lu_sources',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_types_lookup',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('paper_trading_positions',
    sa.Column('position_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('market_id', sa.VARCHAR(length=68), nullable=False),
    sa.Column('outcome', sa.VARCHAR(length=4), nullable=False),
    sa.Column('stake', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('execution_stake', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('avg_odds', sa.NUMERIC(precision=6, scale=3), nullable=False),
    sa.Column('safebox_fee_bps', sa.SMALLINT(), nullable=False),
    sa.Column('skew_fee_bps', sa.SMALLINT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('opened_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('maturity_date', sa.DATETIME(), nullable=False),
    sa.Column('final_value', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('pnl', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('result', sa.VARCHAR(length=4), nullable=True),
    sa.Column('resolved_outcome', sa.VARCHAR(length=4), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_trading_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('position_id')
    )
    with op.batch_alter_table('paper_trading_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ptp_status_session'), ['status', 'session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ptp_session_market'), ['session_id', 'market_id', 'outcome'], unique=False)
        batch_op.create_index(batch_op.f('idx_ptp_maturity'), ['maturity_date'], unique=False)

    op.create_table('blockchain_migration',
    sa.Column('blockchain_address', sa.TEXT(), nullable=True),
    sa.Column('market_id', sa.TEXT(), nullable=False),
    sa.Column('migrated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('network', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('blockchain_address')
    )
    op.create_table('table_metadata',
    sa.Column('table_name', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_table('odds_archive',
    sa.Column('market_id', sa.VARCHAR(length=68), nullable=False),
    sa.Column('outcome', sa.INTEGER(), nullable=False),
    sa.Column('odds_x1000', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False)
    )
    with op.batch_alter_table('odds_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_odds_archive_market'), ['market_id'], unique=False)

    op.create_table('paper_trading_sessions',
    sa.Column('session_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('session_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('initial_bankroll', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('strategy_config', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('paper_trading_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_pts_created_at'), ['created_at'], unique=False)

    op.drop_table('odds_normalized', schema='ominari')
    with op.batch_alter_table('markets_normalized', schema='ominari') as batch_op:
        batch_op.drop_index(batch_op.f('ix_ominari_markets_normalized_source_id'))

    op.drop_table('markets_normalized', schema='ominari')
    op.drop_table('lu_teams', schema='ominari')
    op.drop_table('lu_sports', schema='ominari')
    op.drop_table('lu_sources', schema='ominari')
    op.drop_table('lu_outcomes', schema='ominari')
    op.drop_table('lu_market_types', schema='ominari')
    # ### end Alembic commands ###
