[project]
name = "beige-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"toml>=0.10.2",
	"openai-whisper",
	"numpy<=2.2",
]

[project.scripts]
transcribe = "beige_book.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["beige_book"]

[dependency-groups]
dev = [
    "ruff>=0.12.4",
]
