name: Beige Book Build and Test

# paths b/c beige-book depends on pinkhaus-models
on:
  push:
    branches: [ main ]
    paths:
      - 'projects/beige-book/**'
      - 'projects/pinkhaus-models/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'projects/beige-book/**'
      - 'projects/pinkhaus-models/**'

jobs:
  build:
    name: "Build and test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Flox"
        uses: "flox/install-flox-action@v2"

      - name: "Activate Flox and run lint/format"
        working-directory: ./projects/beige-book/
        run: |
          flox activate -- just install
          flox activate -- just check

      - name: "Run pytest with Flox"
        working-directory: ./projects/beige-book/
        run: |
          flox activate -- pytest
