name: Build and Test Beige Book Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build and test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Flox"
        uses: "flox/install-flox-action@v2"

      - name: "Build and test"
        uses: "flox/activate-action@v1"
        with:
          command: |
            cd ./projects/beige-book/
            just install
            just check
          dir: ./projects/beige-book/

      - name: "Build and test"
        working-directory: ./projects/beige-book/
        run: |
            souce .venv/bin/activate
            pytest
