name: Build and Test Beige Book Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build and test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install system dependencies"
        run: |
          sudo apt-get update
          # Install C++ runtime and other dependencies needed by PyTorch
          sudo apt-get install -y \
            libstdc++6 \
            libgomp1 \
            libgcc-s1 \
            libc6 \
            libgcc1
          sudo ldconfig

      - name: "Install Flox"
        uses: "flox/install-flox-action@v2"

      - name: "Activate Flox and run lint/format"
        working-directory: ./projects/beige-book/
        run: |
          flox activate -- just install
          flox activate -- just check

      - name: "Run pytest with Flox"
        working-directory: ./projects/beige-book/
        run: |
          flox activate -- uv run pytest
