name: Grant Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  strategy:
    matrix:
      dirs: ["./projects/grant", "./projects/beige-book/", "./projects/pinkhaus-models"]
  build:
    name: "Build and test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Flox"
        uses: "flox/install-flox-action@v2"

      - name: "Activate Flox and run lint/format"
        working-directory: ${{ matrix.dirs }}
        run: |
          flox activate -- just install
          flox activate -- just check

      - name: "Run pytest with Flox"
        working-directory:  ${{ matrix.dirs }}
        run: |
          flox activate -- pytest
